In [2]:
#weight tensor matrix multiplied with weight tensor, then add bias, then take an activation function to get output
import tensorflow as tf

In [4]:
tf.compat.v1.disable_eager_execution()
hello_const = tf.constant('Hello world')
hello_const

<tf.Tensor 'Const:0' shape=() dtype=string>

In [17]:

a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
sess = tf.compat.v1.Session()
print(sess.run(c)) 
print(sess.run(hello_const))
sess.close()

30.0
b'Hello world'


In [22]:
#difference between placeholder and variables?
val1=tf.compat.v1.placeholder(tf.float32)
val2=tf.compat.v1.placeholder(tf.float32)
summ = val1+val2
sess= tf.compat.v1.Session()
#now instead of passing values we can pass dictionary, so it can be consts, arrays, matrices and what not
print(sess.run(summ,feed_dict={val1:[1,2,3,4],val2:[5,6,7,8]}))

[ 6.  8. 10. 12.]


In [25]:
mult = val1*val2
print(sess.run(mult,feed_dict={val1:[[1,2],[3,4]],val2:[[5,6],[7,8]]}))
sess.close()

[[ 5. 12.]
 [21. 32.]]


In [31]:
#variables are trainable parameters to graph... stuff that we can change later on...
#we need to initialise the variable by explicit function... extra layer of protection for running large computation
W1=tf.Variable([0.3],tf.float32)
init=tf.compat.v1.global_variables_initializer()
sess=tf.compat.v1.Session()
sess.run(init)
print(sess.run(W1))
sess.close()


[0.3]


In [10]:
#Y=b+W*X
W=tf.Variable([3.0],tf.float32)
b=tf.Variable([-0.9],tf.float32)
X=tf.compat.v1.placeholder(tf.float32)
linear_model=W*X+b
init=tf.compat.v1.global_variables_initializer()
sess=tf.compat.v1.Session()
sess.run(init)
print(sess.run(linear_model,{X:[1.0,2.0,3.0,4.0,5.0,6.0,7.0]}))
sess.close()

[ 2.1  5.1  8.1 11.1 14.1 17.1 20.1]


In [15]:
#cross entropy loss function for classification problems, and MSC for refgression problems... this is MSC ryt?
Y=tf.compat.v1.placeholder(tf.float32)
sq_delta=tf.square(linear_model-Y)
loss=tf.reduce_sum(sq_delta)

optimizer = tf.compat.v1.train.GradientDescentOptimizer(0.01)
train=optimizer.minimize(loss)

init=tf.compat.v1.global_variables_initializer()
sess=tf.compat.v1.Session()
sess.run(init)

for i in range(30):
    sess.run(train, {X:[1,2,3,4],Y:[0,-1,-2,-3]})

print(sess.run(W),sess.run(b))
#cross entropy... loss= -sum(y*log(p))
#p is probability obtained from softmax ...
#y is the supervised learning outcome. 
#squared optimizer, dont need to worry about local minimas being a problem?


[-0.3075213] [-1.0359718]
